"""create core tables phase1

Revision ID: c4bb117380ee
Revises:
Create Date: 2026-08-24 23:37:40.656228

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c4bb117380ee"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subjects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_subjects_created_at", "subjects", ["created_at"], unique=False)
    op.create_index(op.f("ix_subjects_id"), "subjects", ["id"], unique=False)
    op.create_table(
        "onboarding_answers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("answer", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_onboarding_answers_subject_id"),
        "onboarding_answers",
        ["subject_id"],
        unique=False,
    )
    op.create_table(
        "subject_profile",
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("goal", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("current_level", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("background", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("motivation", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "pace_preference",
            sa.Enum("chill", "steady", "intense", name="pace_preference"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("onboarding", "ready", name="subject_profile_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("subject_id"),
    )
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("prerequisite_ids", postgresql.JSONB(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "active", "done", name="topic_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["subject_id"], ["subjects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_topics_subject_id_order_index",
        "topics",
        ["subject_id", "order_index"],
        unique=False,
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.Enum("user", "assistant", name="chat_role"), nullable=False
        ),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chat_messages_topic_id"),
        "chat_messages",
        ["topic_id"],
        unique=False,
    )
    op.create_table(
        "feed_posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_feed_posts_topic_id_order_index",
        "feed_posts",
        ["topic_id", "order_index"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_feed_posts_topic_id_order_index", table_name="feed_posts")
    op.drop_table("feed_posts")
    op.drop_index(op.f("ix_chat_messages_topic_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index("ix_topics_subject_id_order_index", table_name="topics")
    op.drop_table("topics")
    op.drop_table("subject_profile")
    op.drop_index(
        op.f("ix_onboarding_answers_subject_id"), table_name="onboarding_answers"
    )
    op.drop_table("onboarding_answers")
    op.drop_index(op.f("ix_subjects_id"), table_name="subjects")
    op.drop_index("ix_subjects_created_at", table_name="subjects")
    op.drop_table("subjects")

    sa.Enum(name="chat_role").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="topic_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="subject_profile_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="pace_preference").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
